import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/module.dart';
import '../models/roles.dart';
import '../../features/auth/providers/auth_providers.dart';

final allModulesProvider = Provider<List<AppModule>>((ref) {
  return [
    AppModule(
      id: 'dashboard',
      name: 'Dashboard',
      icon: Icons.dashboard_outlined,
      route: '/home/dashboard',
      allowedRoles: {UserRole.owner, UserRole.manager, UserRole.employee},
      description: 'KPIs, production stats, and alerts',
    ),
    AppModule(
      id: 'pos',
      name: 'POS Ops',
      icon: Icons.point_of_sale_outlined,
      route: '/home/pos',
      allowedRoles: {UserRole.owner, UserRole.manager, UserRole.employee},
      description: 'Orders, tables, KDS, coupons, modifiers',
    ),
    AppModule(
      id: 'reports',
      name: 'Reports',
      icon: Icons.analytics_outlined,
      route: '/home/reports',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Filtered exports and charts',
    ),
    AppModule(
      id: 'projects',
      name: 'Projects',
      icon: Icons.view_timeline_outlined,
      route: '/home/projects',
      allowedRoles: {UserRole.owner, UserRole.manager, UserRole.employee},
      description: 'Projects, tasks, change requests',
    ),
    AppModule(
      id: 'employees',
      name: 'Employees',
      icon: Icons.group_outlined,
      route: '/home/employees',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Role & department management',
    ),
    AppModule(
      id: 'hr',
      name: 'HR',
      icon: Icons.badge_outlined,
      route: '/home/hr',
      allowedRoles: {UserRole.owner, UserRole.manager, UserRole.employee},
      description: 'Profiles, requests, and documents',
    ),
    AppModule(
      id: 'inventory',
      name: 'Inventory',
      icon: Icons.inventory_2_outlined,
      route: '/home/inventory',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Items, recipes, suppliers, transactions',
    ),
    AppModule(
      id: 'erp',
      name: 'ERP',
      icon: Icons.business_outlined,
      route: '/home/erp',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Sites, departments, BOMs',
    ),
    AppModule(
      id: 'mes',
      name: 'MES',
      icon: Icons.precision_manufacturing_outlined,
      route: '/home/mes',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Lines, work orders, events',
    ),
    AppModule(
      id: 'plm',
      name: 'PLM',
      icon: Icons.design_services_outlined,
      route: '/home/plm',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Designs, engineering changes, docs',
    ),
    AppModule(
      id: 'scm',
      name: 'SCM',
      icon: Icons.local_shipping_outlined,
      route: '/home/scm',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Suppliers, POs, inbound, demand',
    ),
    AppModule(
      id: 'wms',
      name: 'WMS',
      icon: Icons.warehouse_outlined,
      route: '/home/wms',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Warehouses, bins, lots, transfers',
    ),
    AppModule(
      id: 'qms',
      name: 'QMS',
      icon: Icons.fact_check_outlined,
      route: '/home/qms',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Inspections, NCRs, CAPA, audits',
    ),
    AppModule(
      id: 'attendance',
      name: 'Attendance',
      icon: Icons.schedule_outlined,
      route: '/home/attendance',
      allowedRoles: {UserRole.owner, UserRole.manager, UserRole.employee},
      description: 'Daily logs, overtime, missing check-ins',
    ),
    AppModule(
      id: 'salaries',
      name: 'Salaries',
      icon: Icons.payments_outlined,
      route: '/home/salaries',
      allowedRoles: {UserRole.owner, UserRole.manager, UserRole.employee},
      description: 'Payroll history and adjustments',
    ),
    AppModule(
      id: 'hrms',
      name: 'HRMS',
      icon: Icons.assignment_ind_outlined,
      route: '/home/hrms',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Contracts, payroll runs, leave, training',
    ),
    AppModule(
      id: 'cmms',
      name: 'CMMS',
      icon: Icons.build_outlined,
      route: '/home/cmms',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Assets, maintenance plans & WO, parts',
    ),
    AppModule(
      id: 'finance',
      name: 'Finance',
      icon: Icons.account_balance_outlined,
      route: '/home/finance',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Ledger, journals, AP/AR',
    ),
    AppModule(
      id: 'crm',
      name: 'CRM',
      icon: Icons.handshake_outlined,
      route: '/home/crm',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Accounts, contacts, leads, cases',
    ),
    AppModule(
      id: 'bi',
      name: 'BI',
      icon: Icons.data_exploration_outlined,
      route: '/home/bi',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Dashboards, KPIs, snapshots',
    ),
    AppModule(
      id: 'hse',
      name: 'HSE',
      icon: Icons.health_and_safety_outlined,
      route: '/home/hse',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Incidents, audits, actions, training',
    ),
    AppModule(
      id: 'dms',
      name: 'DMS',
      icon: Icons.folder_open_outlined,
      route: '/home/dms',
      allowedRoles: {UserRole.owner, UserRole.manager, UserRole.employee},
      description: 'Folders, documents, versions',
    ),
    AppModule(
      id: 'visitor',
      name: 'Visitor',
      icon: Icons.badge_outlined,
      route: '/home/visitor',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Visitor registration and entries',
    ),
    AppModule(
      id: 'iot',
      name: 'IoT',
      icon: Icons.sensors_outlined,
      route: '/home/iot',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Devices, sensors, readings',
    ),
    AppModule(
      id: 'procurement',
      name: 'Procurement',
      icon: Icons.shopping_bag_outlined,
      route: '/home/procurement',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Vendors, tenders, responses, PRs',
    ),
    AppModule(
      id: 'commerce',
      name: 'Commerce',
      icon: Icons.storefront_outlined,
      route: '/home/commerce',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Customers and orders',
    ),
    AppModule(
      id: 'budgeting',
      name: 'Budgeting',
      icon: Icons.savings_outlined,
      route: '/home/budgeting',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Cost centers, budgets, actuals, exports',
    ),
    AppModule(
      id: 'communication',
      name: 'Communication',
      icon: Icons.campaign_outlined,
      route: '/home/communication',
      allowedRoles: {UserRole.owner, UserRole.manager},
      description: 'Announcements & workflow actions',
    ),
    AppModule(
      id: 'platform',
      name: 'Platform',
      icon: Icons.layers_outlined,
      route: '/home/platform',
      allowedRoles: {UserRole.owner},
      description: 'Tenants, modules, user access',
    ),
    AppModule(
      id: 'notifications',
      name: 'Notifications',
      icon: Icons.notifications_outlined,
      route: '/home/notifications',
      allowedRoles: {UserRole.owner, UserRole.manager, UserRole.employee},
      description: 'Events and activity logs',
    ),
  ];
});

final allowedModulesProvider = Provider<List<AppModule>>((ref) {
  final role = ref.watch(currentRoleProvider) ?? UserRole.employee;
  return ref
      .watch(allModulesProvider)
      .where((module) => module.allowedRoles.contains(role))
      .toList(growable: false);
});

final selectedModuleIdProvider = StateProvider<String>((ref) => 'dashboard');
